name: 'terraform-kubernetes-addons'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: 'linter'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_STATES: false
        VALIDATE_KUBERNETES_KUBEVAL: false
        VALIDATE_TERRAFORM_TERRASCAN: false
    - name: 'slack:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger

  terraform-generic:
    name: 'terraform:generic'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: 'slack:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger

  terraform-aws:
    name: 'terraform:aws'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: modules/aws

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: modules/aws

    - name: Terraform Validate
      run: terraform validate
      working-directory: modules/aws
      env:
        AWS_REGION: eu-west-3

    - name: 'slack:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger

  terraform-scaleway:
    name: 'terraform:scaleway'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: modules/scaleway

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: modules/scaleway

    - name: Terraform Validate
      run: terraform validate
      working-directory: modules/scaleway

    - name: 'slack:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger

  terraform-release:
    name: 'terraform:release'
    runs-on: ubuntu-latest
    needs:
      - linter
      - terraform-generic
      - terraform-aws
      - terraform-scaleway
    steps:
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main'

    - name: 'slack:success'
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: SUCCESS
        color: good

    - name: 'slack:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger
